import { Dimensions, StyleSheet } from "react-native";

import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    // paddingHorizontal: wp(4),
  },

  filterButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'relative',
  },
  filterButtonText: {
    fontSize: wp("3.5%"),
    color: "#000",
    fontFamily: "Poppins-Medium",
    marginLeft: wp("2%"),
  },
  filterBadge: {
    position: 'absolute',
    top: -8,
    right: -8,
    backgroundColor: '#FF0303',
    borderRadius: wp("3%"),
    minWidth: wp("4%"),
    height: wp("4%"),
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  filterBadgeText: {
    color: '#fff',
    fontSize: wp("2.5%"),
    fontWeight: 'bold',
  },
  activeFiltersContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: wp('4%'),
    paddingVertical: hp('1%'),
    backgroundColor: '#f8f8f8',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  activeFiltersText: {
    fontSize: wp('3.2%'),
    color: '#666',
    fontFamily: 'Poppins-Medium',
  },
  clearAllButton: {
    paddingHorizontal: wp('3%'),
    paddingVertical: hp('0.5%'),
  },
  clearAllText: {
    fontSize: wp('3.2%'),
    color: '#FF0303',
    fontFamily: 'Poppins-Medium',
  },
  selectedFiltersContainer: {
    paddingHorizontal: wp('4%'),
    paddingVertical: hp('1%'),
    backgroundColor: '#f0f0f0',
  },
  selectedFiltersRow: {
    flexDirection: 'row',
    gap: wp('2%'),
  },
  selectedFilterChip: {
    backgroundColor: '#6C63FF',
    paddingHorizontal: wp('3%'),
    paddingVertical: hp('0.5%'),
    borderRadius: wp('2%'),
  },
  selectedFilterText: {
    color: '#fff',
    fontSize: wp('2.8%'),
    fontFamily: 'Poppins-Medium',
  },
  debugInfo: {
    backgroundColor: '#f0f0f0',
    padding: wp('2%'),
    marginHorizontal: wp('4%'),
    borderRadius: 5,
    marginTop: hp('1%'),
  },
  debugText: {
    fontSize: wp('2.8%'),
    color: '#666',
    textAlign: 'center',
    fontFamily: 'Poppins-Medium',
    marginBottom: hp('0.5%'),
  },
  loadingText: {
    fontSize: wp('3%'),
    color: '#999',
    textAlign: 'center',
    marginTop: hp('1%'),
    fontFamily: 'Poppins-Medium',
  },
  // Search and Filter Styles
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: wp(2),
    paddingHorizontal: wp(3),
    marginBottom: hp(0.5),
    marginVertical: hp(1),
    // marginHorizontal: wp(3.9),
  },
  searchInput: { flex: 1, fontSize: hp(1.5), color: "#000" },

  /** Filters */
  filtersRow: {
    flexDirection: "row",
    marginVertical: hp(2),
    alignItems: "center",
  },
  filterBtn: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: hp(0.8),
    paddingHorizontal: wp(3.5),
    marginRight: wp(2.5),
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: wp(2),
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 3,
    elevation: 2,
  },
  activeFilterBtn: {
    borderColor: "#6A5AE0",
    backgroundColor: "#f0f0ff",
  },
  filterText: {
    fontSize: hp(1.5),
    color: "#666",
  },
  activeFilterText: {
    color: "#6A5AE0",
    fontWeight: "600",
  },

  listContainer: {
    paddingBottom: hp(2),
  },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: hp(10),
  },
  emptyText: {
    fontSize: wp(4),
    color: "#666",
    textAlign: "center",
  },
  // Existing card styles remain the same...
  card: {
    backgroundColor: "#fff",
    borderRadius: wp(3),
    marginBottom: hp(1),
    overflow: "hidden",
    borderColor: "#eee",
    borderWidth: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  profileSection: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: wp(4),
    paddingVertical: hp(1.5),
  },
  profileImage: {
    width: wp(10),
    height: wp(10),
    borderRadius: wp(5),
  },
  profileName: {
    fontSize: hp(1.8),
    fontWeight: "700",
    color: "#000",
  },
  profileRole: {
    fontSize: hp(1.4),
    color: "#555",
    marginLeft: wp(1),
  },
  verifyIcon: {
    width: wp(3),
    height: wp(3),
    resizeMode: "contain",
    marginLeft: wp(1),
  },
  profileLocation: {
    fontSize: hp(1.3),
    color: "#6E533F",
    marginLeft: wp(1),
    flexShrink: 1,
  },
  profileLocationRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: hp(0.3),
  },
  socialIconButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 8,
    marginVertical: 5,
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
    borderWidth: 0,
    borderColor: "transparent",
  },
  navigationButton: {
    borderColor: "#ddd",
    borderWidth: 1,
    borderRadius: 20,
    padding: 5,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 5,
  },
  imageWrapper: {
    position: "relative",
    width: width - wp(8), // Adjust for container padding
    borderBottomRightRadius: wp(4),
    overflow: "hidden",
  },
  cardImage: {
    width: width - wp(8),
    height: hp(22),
    resizeMode: "cover",
  },
  likeNewTag: {
    position: "absolute",
    top: hp(0),
    left: wp(-1),
    backgroundColor: "#6C63FF",
    paddingHorizontal: wp(3),
    paddingVertical: hp(0.4),
    borderBottomRightRadius: wp(10),
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 2,
  },
  likeNewText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: hp(1),
  },
  sellTag: {
    position: "absolute",
    bottom: 0,
    left: 0,
    paddingHorizontal: wp(3),
    minHeight: hp(2.8),
    justifyContent: "center",
    alignItems: "flex-start",
    overflow: "visible",
    zIndex: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 2,
  },
  sellTagSvg: {
    position: "absolute",
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
  },
  sellTagLabel: {
    flexDirection: "row",
    alignItems: "center",
    height: "100%",
  },

   logoIcon: {
    position: "absolute",
    bottom: 15,
    left: -10,
    // backgroundColor: "white",
    // paddingHorizontal: wp(3),
    // paddingVertical: hp(0.2),
    // flexDirection: "row",
    // alignItems: "center",
  
  },
  sellTagTriangle: {
    position: "absolute",
    right: -wp(4),
    top: 0,
    width: wp(4),
    height: hp(1.4),
    backgroundColor: "white",
    transform: [{ skewX: "35deg" }],
  },
  sellTagTail: {
    position: "absolute",
    right: -wp(4),
    top: hp(1.1),
    width: wp(4),
    height: hp(2),
    backgroundColor: "white",
  },
  sellText: {
    color: "#00000099",
    fontSize: hp(1.4),
    fontWeight: "600",
  },
  rightActions: {
    position: "absolute",
    top: hp(1),
    right: wp(5),
    flexDirection: "row",
    alignItems: "center",
  },
  rightActionBox: {
    backgroundColor: "rgba(0, 0, 0, 0.13)",
    borderRadius: wp(20),
    paddingHorizontal: wp(2),
    paddingVertical: hp(0.8),
    marginLeft: wp(2),
    flexDirection: "row",
    alignItems: "center",
  },
  rightActionText: {
    fontSize: hp(1.4),
    fontWeight: "500",
    color: "white",
    marginLeft: wp(0.5),
  },
  sliderDots: {
    position: "absolute",
    bottom: hp(1),
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "center",
  },
  dot: {
    width: wp(1),
    height: wp(1),
    borderRadius: wp(1),
    backgroundColor: "#D9D9D9",
    marginHorizontal: 3,
  },
  activeDot: {
    backgroundColor: "#6A5AE0",
  },
  cardContent: {
    paddingHorizontal: wp(4),
    paddingTop: hp(0.8),
    paddingBottom: hp(1.4),
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: hp(0.5),
  },
  rowLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  smallCarImage: {
    width: wp(8),
    height: wp(8),
    resizeMode: "contain",
    marginRight: wp(2),
  },
  rowText: {
    fontSize: hp(1.8),
    color: "#333",
  },
  rowTextBottom: {
    fontSize: hp(1.8),
    color: "black",
    fontWeight: "600",
  },
  rowRightText: {
    fontSize: hp(1.3),
    color: "#444",
  },
  rowRightTextBottom: {
    fontSize: hp(1.8),
    fontWeight: "600",
    color: "black",
  },
  bottomActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: wp(4),
    paddingVertical: hp(1.5),
    borderTopWidth: 1,
    borderTopColor: "#eee",
  },
  bottomLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  callIconContainer: {
    backgroundColor: "#fff",
    borderRadius: wp(6),
    padding: wp(2),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 5,
    marginRight: wp(2),
  },
  socialIcon: {
    width: wp(7),
    height: wp(7),
    resizeMode: "contain",
    marginHorizontal: wp(1),
  },
  bottomRight: {
    flexDirection: "row",
    alignItems: "center",
  },
  messageButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: hp(0.8),
    paddingHorizontal: wp(4),
    borderRadius: wp(6),
    marginRight: wp(1),
    borderColor: "#6C63FF",
    borderWidth: 1,
  },
  messageText: {
    color: "#6C63FF",
    fontSize: hp(1.4),
    marginLeft: wp(1),
    fontFamily: "Poppins-Medium",
  },
  iconButton: {
    padding: wp(2),
  },
  scrollContainer: {
    paddingVertical: wp("3%"),
    alignItems: "center",
  },
  button: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: wp("3%"),
    paddingVertical: hp("0.8%"),
    paddingHorizontal: wp("3%"),
    marginRight: wp("3%"),
    backgroundColor: "#fff",
  },
  activeButton: {
    backgroundColor: "#000",
    borderColor: "#000",
  },
  buttonText: {
    fontSize: wp("2.8%"),
    color: "#000",
    fontFamily: "Poppins-Medium",
    marginTop: hp(0.2),
  },
  activeButtonText: {
    color: "#fff",
  },
});
