import { StyleSheet, Platform, StatusBar } from "react-native";
import {
    widthPercentageToDP as wp,
    heightPercentageToDP as hp,
} from "react-native-responsive-screen";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#fff",
    },
    header: {
        paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0,
        backgroundColor: "#fff",
        borderBottomWidth: 1,
        borderBottomColor: "#f0f0f0",
    },
    normalHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: wp(4),
        paddingVertical: hp(1.5),
    },
    headerLeft: {
        flexDirection: "row",
        alignItems: "center",
    },
    headerTitle: {
        fontSize: wp(5),
        fontFamily: "Inter-Bold",
        color: "#000",
        marginLeft: wp(3),
    },
    rightIcons: {
        flexDirection: "row",
        alignItems: "center",
    },
    menuButton: {
        padding: wp(1),
        marginLeft: wp(2),
    },
    actionText: {
        fontSize: wp(3.5),
        color: "#007AFF",
        fontFamily: "Inter-Medium",
    },
    tabs: {
        flexDirection: "row",
        paddingHorizontal: wp(4),
        borderBottomWidth: 1,
        borderBottomColor: "#f0f0f0",
    },
    tabBtn: {
        marginRight: wp(6),
        paddingVertical: hp(1.5),
        alignItems: "center",
    },
    tabText: {
        fontSize: wp(4),
        color: "#999",
        fontFamily: "Inter-Medium",
    },
    activeText: {
        color: "#000",
        fontFamily: "Inter-SemiBold",
    },
    tabUnreadDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: "red",
        marginLeft: 4,
    },
    activeIndicator: {
        position: "absolute",
        bottom: 0,
        width: "100%",
        height: 3,
        backgroundColor: "#000",
        borderRadius: 1.5,
    },
    searchBar: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#f5f5f5",
        marginHorizontal: wp(4),
        marginVertical: hp(2),
        paddingHorizontal: wp(3),
        paddingVertical: Platform.OS === "ios" ? hp(1.2) : hp(0.5),
        borderRadius: 10,
    },
    searchInput: {
        flex: 1,
        fontSize: wp(4),
        color: "#000",
        fontFamily: "Inter-Regular",
        marginLeft: wp(2),
    },
    chatCard: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: hp(1.5),
        borderBottomWidth: 1,
        borderBottomColor: "#f9f9f9",
    },
    // checkboxContainer/checkbox styles removed or kept if needed for revert, 
    // but code now uses inline styles for the overlay.
    // I'll keep them just in case related code is still there or reverted.
    checkboxContainer: {
        marginRight: wp(2),
    },
    checkbox: {
        width: 20,
        height: 20,
        borderRadius: 10,
        borderWidth: 1.5,
        borderColor: "#ccc",
        alignItems: "center",
        justifyContent: "center",
    },
    checkboxSelected: {
        backgroundColor: "#4CAF50",
        borderColor: "#4CAF50",
    },
    profileCircle: {
        position: "relative",
        width: wp(13),
        height: wp(13),
        borderRadius: wp(6.5),
    },
    avatar: {
        width: "100%",
        height: "100%",
        borderRadius: wp(6.5),
        backgroundColor: "#ccc",
        alignItems: "center",
        justifyContent: "center",
    },
    avatarText: {
        fontSize: wp(5),
        color: "#fff",
        fontFamily: "Inter-Bold",
    },
    onlineBadge: {
        position: "absolute",
        bottom: 0,
        right: 0,
        borderWidth: 2,
        borderColor: "#fff",
        borderRadius: 10,
        backgroundColor: "#fff",
    },
    storyBadge: {
        position: "absolute",
        top: 0,
        right: 0,
    },
    statusDot: {
        width: 10,
        height: 10,
        borderRadius: 5,
        borderWidth: 1.5,
        borderColor: "#fff",
    },
    unreadBadge: {
        position: "absolute",
        top: -5,
        right: -5,
        backgroundColor: "red",
        borderRadius: 10,
        minWidth: 18,
        height: 18,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 4,
        borderWidth: 1.5,
        borderColor: "#fff",
    },
    unreadText: {
        color: "#fff",
        fontSize: 10,
        fontWeight: "bold",
    },
    rowBetween: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 2,
    },
    userName: {
        fontSize: wp(4),
        fontFamily: "Inter-SemiBold",
        color: "#000",
        maxWidth: wp(50),
    },
    dateText: {
        fontSize: wp(3),
        color: "#999",
        fontFamily: "Inter-Regular",
    },
    userSub: {
        fontSize: wp(3.5),
        color: "#666",
        fontFamily: "Inter-Regular",
        marginBottom: 2,
        maxWidth: wp(60),
    },
    messageText: {
        fontSize: wp(3.5),
        color: "#888",
        fontFamily: "Inter-Regular",
        flex: 1,
        marginRight: wp(2),
    },
    unreadMessageText: {
        color: "#000",
        fontFamily: "Inter-SemiBold",
    },
    timeText: {
        fontSize: wp(3),
        color: "#999",
    },
    emptyState: {
        alignItems: "center",
        justifyContent: "center",
        marginTop: hp(10),
    },
    emptyStateTitle: {
        fontSize: wp(4.5),
        color: "#000",
        marginTop: hp(2),
        fontFamily: "Inter-SemiBold",
    },
    emptyStateText: {
        fontSize: wp(3.5),
        color: "#999",
        marginTop: hp(1),
        textAlign: "center",
        fontFamily: "Inter-Regular",
        width: "70%",
    },
});
